language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.17.0 # minimum supported version
env:
  - CC=gcc
  - CC=clang
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake
script:
  - cargo build --target x86_64-unknown-linux-gnu && cargo test --target x86_64-unknown-linux-gnu
after_success:
  - ([[ $CC == "gcc" ]] && rustc --version | grep -q nightly) && (cargo install --force cargo-travis; cargo coveralls --exclude-pattern=sss/)
