language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - CC=gcc
  - CC=clang
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
script:
  - cargo build --target x86_64-unknown-linux-gnu && cargo test --target x86_64-unknown-linux-gnu
after_success:
  - ([[ $CC == "gcc" ]] && rustc --version | grep -q nightly) && (cargo install cargo-kcov; cargo kcov --print-install-kcov-sh | sh; cargo kcov --coveralls -- --verify --exclude-pattern=sss/)
