[package]
name = "shamirsecretsharing"
version = "0.1.3"
authors = ["Daan Sprenkels <daan@dsprenkels.com>"]
description = "Shamir secret sharing library for Rust"
license = "MIT"
repository = "https://github.com/dsprenkels/sss-rs"
categories = ["cryptography"]

[badges]
travis-ci = { repository = "dsprenkels/sss-rs", branch = "master" }
maintenance = { status = "passively-maintained" }

[features]
have_libsodium = []

[dependencies]
libc = "0.2.0"

[dev-dependencies]
chacha20-poly1305-aead = "0.1"
rand = "0.7"

[build-dependencies]
cc = "1.0"
