[package]
name = "shamirsecretsharing"
version = "0.1.1"
authors = ["Daan Sprenkels <hello@dsprenkels.com>"]
description = "Shamir secret sharing library for Rust"
license = "MIT"
repository = "https://github.com/dsprenkels/sss-rs"

[dependencies]
libc = "0.2.0"

[dev-dependencies]
chacha20-poly1305-aead = "0.1"
rand = "0.3"

[build-dependencies]
cc = "1.0"
